# Generated by Django 4.2.7 on 2026-05-14 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('brand_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=55)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_brands',
            },
        ),
        migrations.CreateModel(
            name='item_type',
            fields=[
                ('item_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_type', models.CharField(max_length=55)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_item_types',
            },
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('inventory_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=55)),
                ('recieved_date', models.DateField()),
                ('shipper', models.CharField(max_length=255)),
                ('Stock', models.CharField(max_length=255)),
                ('item_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_sys.brand')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_sys.item_type')),
            ],
            options={
                'db_table': 'tbl_inventory',
            },
        ),
    ]
